version: "2"
linters:
  enable:
    - errorlint
    - gocritic
    - misspell
    - revive
    - unconvert
    - bodyclose
    - noctx
  exclusions:
    rules:
      - path: _test\.go
        linters: [noctx]
