//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodePolicy) DeepCopyInto(out *GPUNodePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodePolicy.
func (in *GPUNodePolicy) DeepCopy() *GPUNodePolicy {
	if in == nil {
		return nil
	}
	out := new(GPUNodePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodePolicyList) DeepCopyInto(out *GPUNodePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUNodePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodePolicyList.
func (in *GPUNodePolicyList) DeepCopy() *GPUNodePolicyList {
	if in == nil {
		return nil
	}
	out := new(GPUNodePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodePolicySpec) DeepCopyInto(out *GPUNodePolicySpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RecoveryPeriod != nil {
		in, out := &in.RecoveryPeriod, &out.RecoveryPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.StaleAfter != nil {
		in, out := &in.StaleAfter, &out.StaleAfter
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(int32)
		**out = **in
	}
	if in.MaxUnavailablePercent != nil {
		in, out := &in.MaxUnavailablePercent, &out.MaxUnavailablePercent
		*out = new(int32)
		**out = **in
	}
	if in.DrainScope != nil {
		in, out := &in.DrainScope, &out.DrainScope
		*out = new(DrainScope)
		**out = **in
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodePolicySpec.
func (in *GPUNodePolicySpec) DeepCopy() *GPUNodePolicySpec {
	if in == nil {
		return nil
	}
	out := new(GPUNodePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodePolicyStatus) DeepCopyInto(out *GPUNodePolicyStatus) {
	*out = *in
	if in.QuarantinedNodeNames != nil {
		in, out := &in.QuarantinedNodeNames, &out.QuarantinedNodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodePolicyStatus.
func (in *GPUNodePolicyStatus) DeepCopy() *GPUNodePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GPUNodePolicyStatus)
	in.DeepCopyInto(out)
	return out
}
